Repository fuchicorp/cluster-infrastructure, pull requests merged in 2020-04, with the labels that each got.

#28 added terraform files for adding users to GCP
  google_members/README.md
  google_members/api.tf
  google_members/main.tf
  google_members/provider.tf
  google_members/variables.tf
Labels: DevOps Documentation

#35 created datasource for cluster version
  kube-cluster/kubecluster-deployment.tf
  kube-cluster/variables.tf
Labels: Dev Feature

#36 deleted region for a bucket
  kube-cluster/google_bucket.tf
Labels: DevOps Bug
